name: Build and publish on push
on: [push]
jobs:
  build_and_publish:
    name: Build and publish
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash ; source ~/.bashrc
      - name: Install npm
        run: ~/.nvm/nvm.sh install npm
      - name: Build
        run: npm install; npm run build
      - name: Deploy
        run: cd ./dist; ls
