name: Build and publish on push
on: [push]
jobs:
  build_and_publish:
    name: Build and publish
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: export NVM_DIR="$HOME/.nvm";export PATH=$PATH:/home/0Davgi0/.nvm/versions/node/v18.18.1/bin; npm install; npm run build
      - name: Deploy
        uses: joutvhu/ftp-transfer@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            ls
    
    
