name: Build and Deploy on push
on: 
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: export NVM_DIR="$HOME/.nvm";export PATH=$PATH:/home/0Davgi0/.nvm/versions/node/v18.18.1/bin; npm install; npm run build
      - name: Deploy
        uses: sand4rt/ftp-deployer@v1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_folder: dist
          remote_folder: ./public_html/cocktails
          cleanup: true
          include: "['.htaccess', 'dist/**']"
    
