name: Build and publish on push
on: [push]
jobs:
  build_and_publish:
    name: Build and publish
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: ~/.nvm/versions/node/v16.20.2/bin/npm install; ~/.nvm/versions/node/v16.20.2/bin/npm run build
      - name: Deploy
        run: cd ./dist; ls
